### ISSUE TITLE
launchy-2.4.3 does not work with generate_html()

### ISSUE THREAD

**Issue by kozo2** [ash1day/rbplotly#12]
```
require 'rbplotly'

x = [0, 1, 2, 3, 4]
trace0 = { x: x, y: [0, 2, 1, 4, 3], type: :scatter, mode: :lines }
trace1 = { x: x, y: [4, 1, 3, 0, 2], type: :scatter, mode: :'markers+lines' }
data = [trace0, trace1] # data must be an array

layout = { width: 500, height: 500 }

plot = Plotly::Plot.new(data: data, layout: layout)

plot.layout.height = 300 # You can assign plot's attributes.

plot.generate_html(path: './line_chart.html')
```
fails with
```
Traceback (most recent call last):
        5: from hoge.rb:14:in `<main>'
        4: from /usr/local/bundle/gems/rbplotly-0.1.2/lib/plotly/offline/exportable.rb:20:in `generate_html'
        3: from /usr/local/bundle/gems/launchy-2.4.3/lib/launchy.rb:29:in `open'
        2: from /usr/local/bundle/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:78:in `open'
        1: from /usr/local/bundle/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:67:in `cmd_and_args'
/usr/local/bundle/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:63:in `browser_cmdline': Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new (Launchy::CommandNotFoundError)
```

```
~# ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
```

**Comment by kozo2** [comment]
The cause of error was due to running this in no web browser env.
I close this issue.
